/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

/**
 *
 * @author mangal
 */
public class H_pg extends javax.swing.JFrame {

    /**
     * Creates new form H_pg
     */
    public H_pg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logo = new javax.swing.JLabel();
        btn_nj = new javax.swing.JButton();
        btn_val = new javax.swing.JButton();
        btn_uj = new javax.swing.JButton();
        btn_jop = new javax.swing.JButton();
        btn_job = new javax.swing.JButton();
        btn_jon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREATE GRAPHICS");

        lbl_logo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(221, 34, 57));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setText("CREATE GRAPHICS");

        btn_nj.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_nj.setText("New Job");
        btn_nj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_njActionPerformed(evt);
            }
        });

        btn_val.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_val.setText("View All Jobs ");
        btn_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_valActionPerformed(evt);
            }
        });

        btn_uj.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_uj.setText("UNPAID JOBS");
        btn_uj.setName("btn_lg\n"); // NOI18N
        btn_uj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ujActionPerformed(evt);
            }
        });

        btn_jop.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_jop.setText("Job On Print");
        btn_jop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jopActionPerformed(evt);
            }
        });

        btn_job.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_job.setText("Job On Binding");
        btn_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jobActionPerformed(evt);
            }
        });

        btn_jon.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_jon.setText("Job On Num.");
        btn_jon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_val, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nj, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_uj, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_job, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jon, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_nj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btn_uj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btn_val, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btn_jon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btn_job, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_njActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_njActionPerformed
        // TODO add your handling code here:
        NJ_pg f = new NJ_pg();
        f.show();
        this.hide();
        
    }//GEN-LAST:event_btn_njActionPerformed

    private void btn_jopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jopActionPerformed
        // TODO add your handling code here:
        JP_pg f= new JP_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_jopActionPerformed

    private void btn_jonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jonActionPerformed
        // TODO add your handling code here:
        JN_pg f = new JN_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_jonActionPerformed

    private void btn_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jobActionPerformed
        // TODO add your handling code here:
        JB_pg f= new JB_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_jobActionPerformed

    private void btn_ujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ujActionPerformed
        // TODO add your handling code here:
        JUP_pg f= new JUP_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_ujActionPerformed

    private void btn_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_valActionPerformed
        // TODO add your handling code here:
        JV_pg f =new JV_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_valActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(H_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(H_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(H_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(H_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new H_pg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_job;
    private javax.swing.JButton btn_jon;
    private javax.swing.JButton btn_jop;
    private javax.swing.JButton btn_nj;
    private javax.swing.JButton btn_uj;
    private javax.swing.JButton btn_val;
    private javax.swing.JLabel lbl_logo;
    // End of variables declaration//GEN-END:variables
}
