/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mangal
 */
public class JP_pg extends javax.swing.JFrame {

    /**
     * Creates new form JP_pg
     */
    public JP_pg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_bl = new javax.swing.ButtonGroup();
        lbl_pnm = new javax.swing.JLabel();
        txt_pnm = new javax.swing.JTextField();
        cbx_pnm = new javax.swing.JComboBox<>();
        lbl_jop = new javax.swing.JLabel();
        txt_jop = new javax.swing.JTextField();
        cbx_jop = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jop = new javax.swing.JTable();
        btn_sn = new javax.swing.JButton();
        btn_jc = new javax.swing.JButton();
        btn_sb = new javax.swing.JButton();
        rbtn_bs = new javax.swing.JRadioButton();
        rbtn_mp = new javax.swing.JRadioButton();
        btn_bk = new javax.swing.JButton();
        btn_rf = new javax.swing.JButton();
        btn_job = new javax.swing.JButton();
        btn_jon = new javax.swing.JButton();
        btn_jop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOB ON PRINT");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lbl_pnm.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        lbl_pnm.setText("PARTY'S NAME");

        txt_pnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pnmActionPerformed(evt);
            }
        });

        cbx_pnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pnmActionPerformed(evt);
            }
        });

        lbl_jop.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        lbl_jop.setText("JOB ON PRINT");

        cbx_jop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_jopActionPerformed(evt);
            }
        });

        tbl_jop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Party Name", "Job", "Colour", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_jop);

        btn_sn.setBackground(new java.awt.Color(153, 255, 102));
        btn_sn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btn_sn.setText("Send On Num.");
        btn_sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_snActionPerformed(evt);
            }
        });

        btn_jc.setBackground(new java.awt.Color(0, 204, 0));
        btn_jc.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btn_jc.setText("Job Completed");
        btn_jc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jcActionPerformed(evt);
            }
        });

        btn_sb.setBackground(new java.awt.Color(102, 255, 0));
        btn_sb.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btn_sb.setText("Send On Binding");
        btn_sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sbActionPerformed(evt);
            }
        });

        btngrp_bl.add(rbtn_bs);
        rbtn_bs.setText("BILL SENT");

        btngrp_bl.add(rbtn_mp);
        rbtn_mp.setText("MONEY PAID");

        btn_bk.setBackground(new java.awt.Color(255, 255, 0));
        btn_bk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_bk.setText("BACK");
        btn_bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bkActionPerformed(evt);
            }
        });

        btn_rf.setBackground(new java.awt.Color(0, 102, 255));
        btn_rf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_rf.setText("REFRESH");
        btn_rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rfActionPerformed(evt);
            }
        });

        btn_job.setBackground(java.awt.Color.orange);
        btn_job.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_job.setText("Job On Binding");
        btn_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jobActionPerformed(evt);
            }
        });

        btn_jon.setBackground(java.awt.Color.orange);
        btn_jon.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_jon.setText("Job On Num.");
        btn_jon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jonActionPerformed(evt);
            }
        });

        btn_jop.setBackground(java.awt.Color.orange);
        btn_jop.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        btn_jop.setText("Job On Print");
        btn_jop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_pnm, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pnm, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbx_pnm, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbx_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(rbtn_bs, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btn_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sb)
                                .addGap(33, 33, 33)
                                .addComponent(btn_jc))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btn_bk, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_rf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_job, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_jon, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(rbtn_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(554, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbx_pnm, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_pnm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_pnm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbx_jop, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(rbtn_bs, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_bk)
                            .addComponent(btn_rf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_jop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_jon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_job, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(325, Short.MAX_VALUE)
                    .addComponent(rbtn_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(200, 200, 200)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tbl_jop.getModel();
        // Clear the existing table
        int rows = model.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                model.removeRow(0);
            }
        }
        // SQL Query
        String query = "SELECT * FROM jobprint";
        try {
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Iterate through the result and display on screen
            while (rs.next()) {
                String pnm = rs.getString("pname");
                String jb = rs.getString("job");
                String colour = rs.getString("colour");
                String dsc = rs.getString("descr");               
                model.addRow(new Object[] {pnm, jb,colour , dsc, });
                cbx_pnm.addItem(pnm);              
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void txt_pnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pnmActionPerformed
        // TODO add your handling code here:
        cbx_jop.removeAllItems();
        String pnam = txt_pnm.getText();
        String query = "SELECT * FROM jobprint where pname = '"+(pnam)+"' ";
        try {
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Iterate through the result and display on screen
            while (rs.next()) {             
                String jb = rs.getString("job");
                cbx_jop.addItem(jb);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_txt_pnmActionPerformed

    private void cbx_pnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pnmActionPerformed
        // TODO add your handling code here:
        txt_pnm.setText(""+cbx_pnm.getSelectedItem());
         String pnam = txt_pnm.getText();
          cbx_jop.removeAllItems();
        
        String query = "SELECT * FROM jobprint where pname = '"+(pnam)+"' ";
        try {
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Iterate through the result and display on screen
            while (rs.next()) {             
                String jb = rs.getString("job");
                cbx_jop.addItem(jb);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
     
    }//GEN-LAST:event_cbx_pnmActionPerformed

    private void btn_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_snActionPerformed
        // TODO add your handling code here:
        String pnam = txt_pnm.getText();
        String jt = txt_jop.getText();
        try {
            String query = "SELECT descr FROM jobprint where pname = '"+(pnam)+"' and job = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            String dscr = rs.getString("descr");                                
            String strSQL = "INSERT INTO jobnum VALUES ('"+(pnam)+"','"+(jt)+"','"+(dscr)+"')";
            JOptionPane.showMessageDialog(this, "Record successfully inserted");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");  
           con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         try {
            String query = "DELETE FROM jobprint where pname = '"+(pnam)+"' and job = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate(query);         
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         JP_pg f= new JP_pg();
        f.show();
        this.hide();
        
    }//GEN-LAST:event_btn_snActionPerformed

    private void cbx_jopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_jopActionPerformed
        // TODO add your handling code here:
        txt_jop.setText(""+cbx_jop.getSelectedItem());
    }//GEN-LAST:event_cbx_jopActionPerformed

    private void btn_bkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bkActionPerformed
        // TODO add your handling code here:
        H_pg f= new H_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_bkActionPerformed

    private void btn_rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rfActionPerformed
        // TODO add your handling code here:
        JP_pg f= new JP_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_rfActionPerformed

    private void btn_jcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jcActionPerformed
        // TODO add your handling code here:
         if (rbtn_mp.isSelected()) 
        {
        String pnam = txt_pnm.getText();
        String jt = txt_jop.getText();
            try {
            String query = "DELETE FROM jobup where pname = '"+(pnam)+"' and jtype = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate(query);         
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
              
        }
         if (rbtn_bs.isSelected()) 
        {
        String pnam = txt_pnm.getText();
        String jt = txt_jop.getText();
                     
           try {
            String query = "SELECT descr FROM jobup where pname = '"+(pnam)+"' and jtype = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            String dscr = rs.getString("descr");
            String query1 = "DELETE FROM jobup where pname = '"+(pnam)+"' and jtype = '"+(jt)+"' ";
            int rs1 = stmt.executeUpdate(query1);
            String strSQL = "INSERT INTO jobup VALUES ('"+(pnam)+"','"+(jt)+"','"+(dscr)+"','BILL SENT')";
            JOptionPane.showMessageDialog(this, "Record successfully inserted");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");  
           con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
          try {
            String pnam = txt_pnm.getText();
            String jt = txt_jop.getText();
            String query = "DELETE FROM jobprint where pname = '"+(pnam)+"' and job = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate(query);         
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }
           JP_pg f= new JP_pg();
       f.show();
        this.hide();   
        
    }//GEN-LAST:event_btn_jcActionPerformed

    private void btn_sbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sbActionPerformed
        // TODO add your handling code here:
         String pnam = txt_pnm.getText();
        String jt = txt_jop.getText();
        try {
            String query = "SELECT descr FROM jobprint where pname = '"+(pnam)+"' and jtype = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            String dscr = rs.getString("descr");                                
            String strSQL = "INSERT INTO jobbind VALUES ('"+(pnam)+"','"+(jt)+"','"+(dscr)+"')";
            JOptionPane.showMessageDialog(this, "Record successfully inserted");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");  
           con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         try {
            String query = "DELETE FROM jobprint where pname = '"+(pnam)+"' and jjob = '"+(jt)+"' ";
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate(query);         
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
          JP_pg f= new JP_pg();
       f.show();
        this.hide();     
    }//GEN-LAST:event_btn_sbActionPerformed

    private void btn_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jobActionPerformed
        // TODO add your handling code here:
        JB_pg f= new JB_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_jobActionPerformed

    private void btn_jonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jonActionPerformed
        // TODO add your handling code here:
        JN_pg f = new JN_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_jonActionPerformed

    private void btn_jopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jopActionPerformed
        // TODO add your handling code here:
        JP_pg f= new JP_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_jopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JP_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JP_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JP_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JP_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JP_pg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bk;
    private javax.swing.JButton btn_jc;
    private javax.swing.JButton btn_job;
    private javax.swing.JButton btn_jon;
    private javax.swing.JButton btn_jop;
    private javax.swing.JButton btn_rf;
    private javax.swing.JButton btn_sb;
    private javax.swing.JButton btn_sn;
    private javax.swing.ButtonGroup btngrp_bl;
    private javax.swing.JComboBox<String> cbx_jop;
    private javax.swing.JComboBox<String> cbx_pnm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_jop;
    private javax.swing.JLabel lbl_pnm;
    private javax.swing.JRadioButton rbtn_bs;
    private javax.swing.JRadioButton rbtn_mp;
    private javax.swing.JTable tbl_jop;
    private javax.swing.JTextField txt_jop;
    private javax.swing.JTextField txt_pnm;
    // End of variables declaration//GEN-END:variables
}
