/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author mangal
 */
public class NJ_pg extends javax.swing.JFrame {

    /**
     * Creates new form NJ_pg
     */
    public NJ_pg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_pn = new javax.swing.JLabel();
        txt_pn = new javax.swing.JTextField();
        lbl_jt = new javax.swing.JLabel();
        txt_jt = new javax.swing.JTextField();
        cbx_jt = new javax.swing.JComboBox<>();
        lbl_doj = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        lbl_sz = new javax.swing.JLabel();
        txt_sz = new javax.swing.JTextField();
        cbx_sz = new javax.swing.JComboBox<>();
        lbl_noc = new javax.swing.JLabel();
        txt_noc = new javax.swing.JTextField();
        cbx_noc = new javax.swing.JComboBox<>();
        lbl_pt = new javax.swing.JLabel();
        txt_pt = new javax.swing.JTextField();
        lbl_cl = new javax.swing.JLabel();
        txt_cl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtar_dsc = new javax.swing.JTextArea();
        lbl_dsc = new javax.swing.JLabel();
        btn_clr = new javax.swing.JButton();
        btn_sv = new javax.swing.JButton();
        btn_bk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEW JOB");

        lbl_pn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_pn.setText("Party's Name");

        lbl_jt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_jt.setText("Job Type");

        txt_jt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jtActionPerformed(evt);
            }
        });

        cbx_jt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BILL BOOKS", "LETTER HEADS", "PAMPHLET", "BROUCHERS", "WEDDING  CARDS", "VISITING CARDS", "BOOKLET", "DESIGN WORK", " " }));
        cbx_jt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_jtActionPerformed(evt);
            }
        });

        lbl_doj.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_doj.setText("Date Of Job");

        lbl_sz.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_sz.setText("Size");

        cbx_sz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LEGAL", "A/4", "A/5", "A/6", "A/8", "A/10", "A/12", "A/16" }));
        cbx_sz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_szActionPerformed(evt);
            }
        });

        lbl_noc.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_noc.setText("No Of Copies");

        cbx_noc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 COPY", "2 COPY", "3 COPY", "4 COPY" }));
        cbx_noc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nocActionPerformed(evt);
            }
        });

        lbl_pt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_pt.setText("PAPER TYPE");

        lbl_cl.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_cl.setText("COLOUR");

        txtar_dsc.setColumns(20);
        txtar_dsc.setRows(5);
        jScrollPane1.setViewportView(txtar_dsc);

        lbl_dsc.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_dsc.setText("description");

        btn_clr.setBackground(new java.awt.Color(255, 0, 0));
        btn_clr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clr.setText("CLEAR");
        btn_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clrActionPerformed(evt);
            }
        });

        btn_sv.setBackground(new java.awt.Color(51, 255, 51));
        btn_sv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sv.setText("SAVE");
        btn_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_svActionPerformed(evt);
            }
        });

        btn_bk.setBackground(new java.awt.Color(255, 255, 0));
        btn_bk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_bk.setText("BACK");
        btn_bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_noc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_noc, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbx_noc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_sz, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_sz, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbx_sz, 0, 281, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_jt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_jt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbx_jt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_doj, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_doj, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dsc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txt_cl))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(btn_clr, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btn_bk, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(btn_sv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_jt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_doj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_doj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_sz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_noc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_noc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_noc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dsc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clr)
                    .addComponent(btn_bk))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(500, Short.MAX_VALUE)
                    .addComponent(btn_sv)
                    .addGap(22, 22, 22)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_jtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_jtActionPerformed
        // TODO add your handling code here:           
        txt_jt.setText(""+cbx_jt.getSelectedItem());    
    }//GEN-LAST:event_cbx_jtActionPerformed

    private void txt_jtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jtActionPerformed
        // TODO add your handling code here:
        String s = txt_jt.getText();
        cbx_jt.setSelectedItem(s);
    }//GEN-LAST:event_txt_jtActionPerformed

    private void cbx_szActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_szActionPerformed
        // TODO add your handling code here:
        txt_sz.setText(""+cbx_sz.getSelectedItem());
    }//GEN-LAST:event_cbx_szActionPerformed

    private void cbx_nocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nocActionPerformed
        // TODO add your handling code here:
        txt_noc.setText(""+cbx_noc.getSelectedItem());
    }//GEN-LAST:event_cbx_nocActionPerformed

    private void btn_bkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bkActionPerformed
        // TODO add your handling code here:
        H_pg f= new H_pg();
        f.show();
        this.hide();
    }//GEN-LAST:event_btn_bkActionPerformed

    private void btn_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clrActionPerformed
        // TODO add your handling code here:
        txt_cl.setText("");
        txt_doj.setText("");
        txt_jt.setText("");
        txt_noc.setText("");
        txt_pn.setText("");
        txt_pt.setText("");
        txt_sz.setText("");
        txtar_dsc.setText("");
    }//GEN-LAST:event_btn_clrActionPerformed

    private void btn_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_svActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            Statement stmt = null;            
            ResultSet rs = null;        // ResultSet for SHOPKEEPER table.                 
            String SQL = "SELECT * FROM newjob";
            stmt = con.createStatement();   // Connection string for  ResultSet - rs.
            rs = stmt.executeQuery(SQL);
            // Data transfer from JTextField control to variables
             String pnm = txt_pn.getText();
             String jt = txt_jt.getText();
             String dj = txt_doj.getText();
             String sz = txt_sz.getText();
             String noc = txt_noc.getText();
             String pt = txt_pt.getText();
             String cl = txt_cl.getText();
             String dsc = txtar_dsc.getText();
            String strSQL = "INSERT INTO newjob VALUES ('"+(pnm)+"','"+(jt)+"','"+(dj)+"','"+(sz)+"','"+(noc)+"','"+(pt)+"','"+(cl)+"','"+(dsc)+"')";
            
            
            JOptionPane.showMessageDialog(this, "Record successfully inserted");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            Statement stmt = null;            
            ResultSet rs = null;        // ResultSet for SHOPKEEPER table.                 
            String SQL = "SELECT * FROM jobprint";
            stmt = con.createStatement();   // Connection string for  ResultSet - rs.
            rs = stmt.executeQuery(SQL);
            // Data transfer from JTextField control to variables
             String pnm = txt_pn.getText();
             String jt = txt_jt.getText();            
             String cl = txt_cl.getText();
             String dsc = txtar_dsc.getText();
            String strSQL = "INSERT INTO jobprint VALUES ('"+(pnm)+"','"+(jt)+"','"+(cl)+"','"+(dsc)+"')";
            
            
            
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();        }
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            Statement stmt = null;            
            ResultSet rs = null;        // ResultSet for SHOPKEEPER table.                 
            String SQL = "SELECT * FROM jobup";
            stmt = con.createStatement();   // Connection string for  ResultSet - rs.
            rs = stmt.executeQuery(SQL);
            // Data transfer from JTextField control to variables
             String pnm = txt_pn.getText();
             String jt = txt_jt.getText();            
             String dsc = txtar_dsc.getText();
            String strSQL = "INSERT INTO jobup(pname,jtype,descr) VALUES ('"+(pnm)+"','"+(jt)+"','"+(dsc)+"')";                                                                                                                                                                                          
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();        }
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/graphics","root","root");
            Statement stmt = null;            
            ResultSet rs = null;        // ResultSet for SHOPKEEPER table.                 
            String SQL = "SELECT * FROM jobview";
            stmt = con.createStatement();   // Connection string for  ResultSet - rs.
            rs = stmt.executeQuery(SQL);
            // Data transfer from JTextField control to variables
             String pnm = txt_pn.getText();
             String jt = txt_jt.getText();            
             String dsc = txtar_dsc.getText();
            String strSQL = "INSERT INTO jobview VALUES ('"+(pnm)+"','"+(jt)+"','"+(dsc)+"')";                                                                                                                                                                                          
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();        }
        txt_cl.setText("");
        txt_doj.setText("");
        txt_jt.setText("");
        txt_noc.setText("");
        txt_pn.setText("");
        txt_pt.setText("");
        txt_sz.setText("");
        txtar_dsc.setText("");
    }//GEN-LAST:event_btn_svActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NJ_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NJ_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NJ_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NJ_pg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NJ_pg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bk;
    private javax.swing.JButton btn_clr;
    private javax.swing.JButton btn_sv;
    private javax.swing.JComboBox<String> cbx_jt;
    private javax.swing.JComboBox<String> cbx_noc;
    private javax.swing.JComboBox<String> cbx_sz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cl;
    private javax.swing.JLabel lbl_doj;
    private javax.swing.JLabel lbl_dsc;
    private javax.swing.JLabel lbl_jt;
    private javax.swing.JLabel lbl_noc;
    private javax.swing.JLabel lbl_pn;
    private javax.swing.JLabel lbl_pt;
    private javax.swing.JLabel lbl_sz;
    private javax.swing.JTextField txt_cl;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_jt;
    private javax.swing.JTextField txt_noc;
    private javax.swing.JTextField txt_pn;
    private javax.swing.JTextField txt_pt;
    private javax.swing.JTextField txt_sz;
    private javax.swing.JTextArea txtar_dsc;
    // End of variables declaration//GEN-END:variables
}
